#!/usr/bin/perl
# vim: sts=4 sw=4 ts=4 expandtab:
use strict;
use warnings;
use Cwd;

my $git_dir = `git rev-parse --git-dir`;
chomp $git_dir;

my $gitids = "$git_dir/gitids.txt";

my $color = 'always';
if (scalar @ARGV && $ARGV[0] =~ /--color=(always|auto|never)/) {
    $color = $1;
    shift @ARGV;
}

open my $git_status, "git -c color.status=$color status @ARGV|"
    or die "Error: $!";

open my $cache, ">$gitids"
    or die "Error: $!";

# Headers
print $cache "cwd: " . getcwd . "\n";
print $cache "\n";

my $c = 1;
while (my $line = <$git_status>) {
    if ($line =~ /^#\t/) {
        $line =~ s/^#/#$c/;
        $c += 1;
    }
    print $line;
    print $cache $line;
}
close $git_status;
close $cache;
